version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    ports:
      - "8089:8000"
    environment:
      - APP_ENV=local
      - LARAVEL_PROJECT_NAME=${LARAVEL_PROJECT_NAME}
      - LARAVEL_REPO=${LARAVEL_REPO}
    networks:
      - app-network
    entrypoint: ["/bin/bash", "-c", "/init.sh laravel && cd /var/www/laravel/$LARAVEL_PROJECT_NAME && php artisan serve --host=0.0.0.0 --port=8000"]

  vue:
    build:
      context: .
      dockerfile: ./vue/Dockerfile
    volumes:
      - ./vue:/app/vue
    ports:
      - "8088:8080"
    environment:
      - VUE_PROJECT_NAME=${VUE_PROJECT_NAME}
      - VUE_REPO=${VUE_REPO}
    networks:
      - app-network
    entrypoint: ["/bin/bash", "-c", "/init.sh vue && cd /app/vue/$VUE_PROJECT_NAME && npm run serve"]

networks:
  app-network:
    driver: bridge
